// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <graphscore/core/graphscore_core.hpp>
#include <graphscore/domain/add_beam_override_command.hpp>
#include <graphscore/domain/add_clef_change_command.hpp>
#include <graphscore/domain/add_dynamic_command.hpp>
#include <graphscore/domain/add_grace_group_command.hpp>
#include <graphscore/domain/add_hairpin_command.hpp>
#include <graphscore/domain/add_input_connector_command.hpp>
#include <graphscore/domain/add_interval_command.hpp>
#include <graphscore/domain/add_node_command.hpp>
#include <graphscore/domain/add_output_connector_command.hpp>
#include <graphscore/domain/add_pedal_span_command.hpp>
#include <graphscore/domain/add_slur_command.hpp>
#include <graphscore/domain/add_tempo_point_command.hpp>
#include <graphscore/domain/add_track_command.hpp>
#include <graphscore/domain/archive_track_command.hpp>
#include <graphscore/domain/articulation.hpp>
#include <graphscore/domain/audition_mix.hpp>
#include <graphscore/domain/bind_output_event_command.hpp>
#include <graphscore/domain/clear_pickdown_command.hpp>
#include <graphscore/domain/clef_lane.hpp>
#include <graphscore/domain/command.hpp>
#include <graphscore/domain/command_history.hpp>
#include <graphscore/domain/command_transaction.hpp>
#include <graphscore/domain/connect_command.hpp>
#include <graphscore/domain/connector.hpp>
#include <graphscore/domain/convert_event_to_rest_command.hpp>
#include <graphscore/domain/create_voice_stream_command.hpp>
#include <graphscore/domain/cut_fragment_command.hpp>
#include <graphscore/domain/delete_measure_command.hpp>
#include <graphscore/domain/delete_notehead_command.hpp>
#include <graphscore/domain/disconnect_command.hpp>
#include <graphscore/domain/duplicate_nodes_command.hpp>
#include <graphscore/domain/event_listener.hpp>
#include <graphscore/domain/event_occurrence.hpp>
#include <graphscore/domain/event_queue.hpp>
#include <graphscore/domain/event_registry.hpp>
#include <graphscore/domain/event_state_machine.hpp>
#include <graphscore/domain/event_style_command.hpp>
#include <graphscore/domain/graph.hpp>
#include <graphscore/domain/graph_position.hpp>
#include <graphscore/domain/insert_measure_command.hpp>
#include <graphscore/domain/marking_style_command.hpp>
#include <graphscore/domain/measure_map.hpp>
#include <graphscore/domain/midi_ownership.hpp>
#include <graphscore/domain/move_clef_change_command.hpp>
#include <graphscore/domain/move_notehead_command.hpp>
#include <graphscore/domain/move_tempo_point_command.hpp>
#include <graphscore/domain/node.hpp>
#include <graphscore/domain/node_timeline.hpp>
#include <graphscore/domain/notation_event.hpp>
#include <graphscore/domain/notation_fragment.hpp>
#include <graphscore/domain/notation_markings.hpp>
#include <graphscore/domain/notation_playback.hpp>
#include <graphscore/domain/notation_validation.hpp>
#include <graphscore/domain/paste_fragment_command.hpp>
#include <graphscore/domain/pickdown_bound_oracle.hpp>
#include <graphscore/domain/pickdown_coordinates.hpp>
#include <graphscore/domain/pickdown_ownership.hpp>
#include <graphscore/domain/plugin_chain.hpp>
#include <graphscore/domain/project.hpp>
#include <graphscore/domain/register_event_command.hpp>
#include <graphscore/domain/remove_beam_override_command.hpp>
#include <graphscore/domain/remove_clef_change_command.hpp>
#include <graphscore/domain/remove_dynamic_command.hpp>
#include <graphscore/domain/remove_event_command.hpp>
#include <graphscore/domain/remove_grace_group_command.hpp>
#include <graphscore/domain/remove_hairpin_command.hpp>
#include <graphscore/domain/remove_input_connector_command.hpp>
#include <graphscore/domain/remove_node_command.hpp>
#include <graphscore/domain/remove_output_connector_command.hpp>
#include <graphscore/domain/remove_pedal_span_command.hpp>
#include <graphscore/domain/remove_slur_command.hpp>
#include <graphscore/domain/remove_tempo_point_command.hpp>
#include <graphscore/domain/reset_route_command.hpp>
#include <graphscore/domain/restore_track_command.hpp>
#include <graphscore/domain/route_geometry.hpp>
#include <graphscore/domain/selection.hpp>
#include <graphscore/domain/set_custom_route_command.hpp>
#include <graphscore/domain/set_event_command.hpp>
#include <graphscore/domain/set_input_connector_name_command.hpp>
#include <graphscore/domain/set_listener_policy_command.hpp>
#include <graphscore/domain/set_measure_key_signature_command.hpp>
#include <graphscore/domain/set_measure_time_signature_command.hpp>
#include <graphscore/domain/set_node_color_command.hpp>
#include <graphscore/domain/set_node_name_command.hpp>
#include <graphscore/domain/set_node_notes_command.hpp>
#include <graphscore/domain/set_node_position_command.hpp>
#include <graphscore/domain/set_output_connector_name_command.hpp>
#include <graphscore/domain/set_output_export_enabled_command.hpp>
#include <graphscore/domain/set_output_priority_command.hpp>
#include <graphscore/domain/set_output_type_command.hpp>
#include <graphscore/domain/set_output_weight_command.hpp>
#include <graphscore/domain/set_pickdown_command.hpp>
#include <graphscore/domain/set_project_dynamic_command.hpp>
#include <graphscore/domain/set_project_name_command.hpp>
#include <graphscore/domain/set_project_tempo_command.hpp>
#include <graphscore/domain/set_start_node_command.hpp>
#include <graphscore/domain/set_tempo_point_command.hpp>
#include <graphscore/domain/set_tie_command.hpp>
#include <graphscore/domain/set_track_gain_command.hpp>
#include <graphscore/domain/set_track_mute_command.hpp>
#include <graphscore/domain/set_track_name_command.hpp>
#include <graphscore/domain/set_track_pan_command.hpp>
#include <graphscore/domain/set_track_solo_command.hpp>
#include <graphscore/domain/staff_layout.hpp>
#include <graphscore/domain/step_accidental_command.hpp>
#include <graphscore/domain/tempo_lane.hpp>
#include <graphscore/domain/tie_chain.hpp>
#include <graphscore/domain/track.hpp>
#include <graphscore/domain/tuplet_command.hpp>
#include <graphscore/domain/validation_service.hpp>
#include <graphscore/domain/vertical_transition.hpp>
#include <graphscore/domain/voice_content.hpp>
#include <graphscore/domain/weighted_selection.hpp>
